version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
    - master
configuration: Debug
before_build:
  - dotnet restore
build_script:
  - dotnet build -c Debug /p:DebugType=full
